donasi1/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = 'donasi1'

urlpatterns = [
    path('', views.donasi_tunai, name='donasi_tunai'),
	path('list_donasitunai/', views.list_donasitunai, name='list_donasitunai')
]

donasinontunai/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = 'donasinontunai'

urlpatterns = [
    path('donasi_nontunai/', views.donasi_nontunai, name='donasi_nontunai'),
    path('list_donasinontunai/', views.list_donasinontunai, name='list_donasinontunai')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('infografis/', views.infografis, name='infografis'),
]

pertanyaan/urls.py
from django.urls import path

from . import views

app_name = 'pertanyaan'

urlpatterns = [
	path('asked_us/', views.asked_us, name='asked_us'),
	path('list_asked/', views.list_asked, name='list_asked')
]

tk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('pertanyaan.urls')),
    path('donasi_tunai/',include('donasi1.urls'),name='donasi1'),
    path('', include('donasinontunai.urls'))
]

donasi1/models.py
from django.db import models

# Create your models here.
class DonasiTunai(models.Model):
	nama = models.CharField('Nama', max_length=120)
	alamat = models.TextField('Alamat')
	kontak = models.CharField('Email atau No. Handphone', max_length=100)
	jumlah = models.CharField('Jumlah Transfer', max_length=50)
	anon = models.BooleanField('Tampilkan sebagai donatur anonim', default=False)

donasinontunai/models.py
from django.db import models

# Create your models here.
class DonasiNonTunai(models.Model):
	nama = models.CharField('Nama', max_length = 120)
	alamat = models.TextField('Alamat')
	kontak = models.CharField('Email atau Nomor Handphone', max_length = 120)
	kebutuhan1 = models.CharField('Kebutuhan Logistik', max_length = 120)
	kebutuhan2 = models.CharField('Kebutuhan Lainnya(Optional)', max_length = 120, blank=True, default='')
	anon = models.BooleanField('Tampilkan sebagai Donatur Anonim', default = False)

main/models.py
from django.db import models

# Create your models here.

pertanyaan/models.py
from django.db import models

# Create your models here.
class Pertanyaan(models.Model):
	nama = models.CharField('Nama', max_length=120)
	kontak = models.CharField('Email atau Nomor Handphone', max_length=120)
	pertanyaan = models.TextField('Pertanyaan')

donasi1/forms.py
from django import forms
from .models import DonasiTunai

# Create your views here.
class DonasiTunaiForm(forms.ModelForm):
    class Meta:
        model = DonasiTunai
        fields = {'nama', 'alamat', 'kontak', 'jumlah', 'anon'}

        widgets = {
            'nama': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Nama Donatur',
                'required':True}),
            'alamat': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'Alamat Donatur',
                'required':True}),
            'kontak': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'e.g.: contoh@email.com / 0213427253',
                'required':True}),
            'jumlah': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'e.g.: Rp10.000',
                'required':True}),
        }

donasinontunai/forms.py
from django import forms
from .models import DonasiNonTunai

class DonasiNonTunaiForm(forms.ModelForm):
    class Meta:
        model = DonasiNonTunai
        fields = '__all__'
        

pertanyaan/forms.py
from django import forms
from .models import Pertanyaan

class Form (forms.ModelForm):
	class Meta:
		model = Pertanyaan
		fields = '__all__'

		error_messages={
			'required':'Please type'
		}

donasi1/views.py
from django.shortcuts import render,redirect
from .forms import DonasiTunaiForm
from .models import DonasiTunai

# Create your views here.
def donasi_tunai(request):
    if request.method == "POST":
        form = DonasiTunaiForm(request.POST or None)
        if form.is_valid:
            form.save()
        return redirect('/donasi_tunai/list_donasitunai')
    else:
        form = DonasiTunaiForm()
        response = {'form' : form}
    return render(request, 'form_donasitunai.html', response)

def list_donasitunai(request):
    donatur = DonasiTunai.objects.all()
    response = {'donatur':donatur}
    return render(request, 'list_donasitunai.html', response)

donasinontunai/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import DonasiNonTunai
from .forms import DonasiNonTunaiForm
# Create your views here.

def donasi_nontunai(request):
    submitted = False
    if request.method == 'POST' :
        form = DonasiNonTunaiForm(request.POST)
        form.save()
        return HttpResponseRedirect('/donasi_nontunai/?submitted=True')
    else :
        form = DonasiNonTunaiForm()
        if 'submitted' in request.GET :
            submitted = True
        context = {'form' : form, 'submitted' : submitted}  

    return render(request, 'form_donasinontunai.html', context)    

def list_donasinontunai(request):
    donatur = DonasiNonTunai.objects.all()
    context = {'donatur' : donatur}
    return render(request, 'list_donasinontunai.html', context)     

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

def faq(request):
	return render(request, 'faq.html')

def infografis(request):
	return render(request, 'infografis.html')

pertanyaan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Form
from .models import Pertanyaan

def asked_us(request):
	submitted = False
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/asked_us/?submitted=True')
	else:
		form = Form()
		if 'submitted' in request.GET:
			submitted = True
		context = {
			'form' : form,
			'submitted' : submitted
		}

	return render(request, 'form_pertanyaan.html', context)

def list_asked(request):
	mylist = Pertanyaan.objects.all()
	return render(request, 'list_result.html', {'mylist':mylist})

donasi1/templates/form_donasitunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Donasi Tunai</title>
{% endblock meta %}

{% block content %}
  <div class="content mt-5 pt-5">
    <h1 class="title">Form Donasi Tunai<br></h1>
  	<div class="form">
  		<form action="" method="POST">
        <h2 class="content_list" style="text-align: center; color: #272343"><strong>Harap mentransfer donasi ke:<br></strong>Bank: ABC<br>No. Rekening: 0123456789<br></h2>
			{% csrf_token %}
        <p>Nama:</p>
        <p>{{form.nama}}</p>
        <p>Alamat:</p>
	    	<p>{{ form.alamat }}</p>
        <p>Email atau No. Handphone:</p>
        <p>{{form.kontak}}</p>
        <p>Jumlah Transfer</p>
        <p>{{form.jumlah}}</p>
        <p>{{form.anon}} Tampilkan sebagai donatur anonim</p>
        <br>
        <h2 class="content_list" style="text-align: center; color: #272343"><strong>Jika sudah mengisi form diatas, <br>
          mohon konfirmasi ke kontak<br>
          di bawah ini:<br></strong>Budi / +62 0812345678<br></h2>
        <input type="submit" value="Kirim" class="btn">
        <a href="{% url 'donasi1:list_donasitunai' %}" class="btn">Daftar Donatur</a>
		</form>
  	</div>
  </div>
{% endblock content %}

donasi1/templates/list_donasitunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Donatur</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Daftar Donatur</h1>
	<table class="table">
		<tr>
			<th scope="col">Nama</th>
			<th scope="col">Jumlah Transfer</th>
		</tr>
		{% for item in donatur %}
		{% if item.anon %}
		<tr>
			<td>Anonim</td>
			<td>{{item.jumlah}}</td>
		</tr>
		{% else %}
		<tr>
			<td>{{item.nama}}</td>
			<td>{{item.jumlah}}</td>
		</tr>
		{% endif %}
		{% endfor %}
		<a href="/donasi_tunai" class="btn">Kembali ke Form Donasi Tunai</a>
	</table>
</div>
{% endblock content %}

donasinontunai/templates/form_donasinontunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Donasi Tunai</title>
{% endblock meta %}

{% block content %}
  <div class="content mt-5 pt-5">
  {% if submitted %}
  <div class="make_center">
  	<h1 class="title">Donasi Anda Sudah Terdata!</h1>
  	<a href="/main" class="btn">Kembali ke Halaman Utama</a>
  	<a href="{% url 'donasinontunai:list_donasinontunai' %}" class="btn">Daftar Donatur</a>
  </div>
  
  {% else %}
    <h1 class="title">Form Donasi Non Tunai<br></h1>
  	<div class="form mt-5">
  		<form action="" method="POST">
		{% csrf_token %}
        <p>Nama:</p>
        <p>{{form.nama}}</p>
        <p>Alamat:</p>
	    	<p>{{ form.alamat }}</p>
        <p>Email atau No. Handphone:</p>
        <p>{{form.kontak}}</p>
        <p>Kebutuhan Logistik</p>
        <p>{{form.kebutuhan1}}</p>
        <p>Kebutuhan Lainnya(Optional)</p>
        <p>{{form.kebutuhan2}}</p>
        <p>{{form.anon}} Tampilkan sebagai donatur anonim</p>
        <br>
        <h2 class="content_list" style="text-align: center; color: #272343"><strong>Setelah mengisi form ini, <br>
          mohon konfirmasi ke kontak<br>
          di bawah ini:<br></strong></h2>
        <h2 class="content_list" style="text-align: center; color: #272343">Budi / +62 0812345678<br></h2>
        <input type="submit" value="Kirim" class="btn mt-5">
        <a href="{% url 'donasinontunai:list_donasinontunai' %}" class="btn mt-5">Daftar Donatur</a>
		</form>
  	</div>
  {% endif %}
  </div>
{% endblock content %}

donasinontunai/templates/list_donasinontunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Donatur</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Daftar Donatur</h1>
	<div class="container mt-5">
		<div class="row">
			<table class="table table-borderless text-center">
				<tr>
					<th scope="col">No</th>
					<th scope="col">Nama</th>
					<th scope="col">Kebutuhan Logistik</th>
					<th scope="col">Kebutuhan Lainnya(Optional)</th>
				</tr>
				{% for x in donatur %}
				{% if x.anon %}
				<tr>
					<td>{{forloop.counter}}</th>
					<td>Anonim</td>
					<td>{{x.kebutuhan1}}</td>
					<td>{{x.kebutuhan2}}</td>
				</tr>
				{% else %}
				<tr>
					<td>{{forloop.counter}}</th>
					<td>{{x.nama}}</td>
					<td>{{x.kebutuhan1}}</td>
					<td>{{x.kebutuhan2}}</td>
				</tr>
				{% endif %}
				{% endfor %}
			</table>
	    <a href="/donasi_nontunai" class="btn mt-5">Kembali ke Form Donasi Non Tunai</a>
		</div>
		
	</div>
  		
</div>
{% endblock content %}

main/templates/faq.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>FAQ</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Frequently Asked Questions</h1>
	<ol class="order_list">
		<li>
			<p class="title_list">Apa itu Physical distancing?</p>
			<p class="content_list">Physical distancing adalah upaya yang dilakukan untuk mencegah penyebaran virus corona di masyarakat. Secara sederhana Physical Distancing adalah menjaga jarak lebih dari 1 meter dengan siapapun. Dengan kata lain: Tidak Berdekatan dan Tidak Berkumpul.
			</p>
		</li>
		<li>
			<p class="title_list">Apa kita perlu pakai masker?</p>
			<p class="content_list">Semua orang harus menggunakan masker kain jika terpaksa beraktivitas di luar rumah.	Kamu bisa menggunakan masker kain tiga lapis yang dapat dicuci dan digunakan berkali-kali, agar masker bedah dan N-95 tersedia bagi petugas medis dan mereka yang sakit.<br><br>
			Jangan lupa untuk mencuci masker kain menggunakan air sabun agar tetap bersih. Penggunaan masker yang keliru justru meningkatkan risiko penularan. <br><br>
			Jangan sentuh atau buka-tutup masker saat digunakan. Tetap jaga jarak minimal 1 meter dengan siapapun, jangan sentuh wajah dan cuci tangan pakai sabun sesering mungkin.
			</p>
		</li>
		<li>
			<p class="title_list">Apa gejala COVID-19?</p>
			<p class="content_list">Gejala COVID-19 yang umum adalah demam, rasa lelah dan batuk kering. Ada juga yang mengalami rasa nyeri dan sakit, hidung tersumbat, pilek, sakit tenggorokan atau diare. Ada juga yang tidak merasakan apa-apa, seperti orang sehat. <br><br>
			Jika kamu pernah berdekatan dengan orang yang memilliki gejala COVID-19 atau berpergian ke tempat terjangkiti, laporkan ke puskesmas terdekat dan lakukan monitoring mandiri. Bila dalam 1-14 hari kemudian mengalami gejala, lakukan isolasi diri.
			Karena orang yang merasa sehat pun bisa saja sedang kena COVID-19.<br><br>
			Kamu bisa hubungi 119 untuk bantuan lebih lanjut. Kalau kondisi memburuk, seperti sesak napas, kontak Rumah Sakit rujukan dan segera periksakan diri.
			</p>
		</li>
		<li>
			<p class="title_list">Apa itu COVID-19?</p>
			<p class="content_list"> COVID-19 adalah singkatan dari CoronaVirus Disease-2019.<br><br>
			COVID-19 adalah penyakit menular yang disebabkan oleh jenis coronavirus yang baru ditemukan. Ini merupakan virus baru dan penyakit yang tidak dikenal sebelum terjadi wabah di Wuhan, Tiongkok, bulan Desember 2019.
			</p>
		</li>
		<li>
			<p class="title_list">Situasi COVID-19 terkini di Indonesia</p>
			<p class="content_list">
			Untuk info peta sebaran kasus COVID-19 bisa klik tautan berikut <a href="https://covid19.go.id/peta-sebaran">https://covid19.go.id/peta-sebaran</a><br>
			Untuk info peta zonasi risiko daerah bisa klik tautan berikut <a href="https://covid19.go.id/peta-risiko">https://covid19.go.id/peta-risiko</a><br>
			Untuk info pemantauan kasus COVID-19 WNA bisa klik tautan berikut <a href="https://covid19.go.id/kasus-wna">https://covid19.go.id/kasus-wna</a>
			</p>
		</li>
	</ol>
	<br>
	<p><strong>Sumber : https://covid19.go.id/tanya-jawab</strong></p>
	<br>
	<h2 class="before_button">Tidak Menemukan Masalah?</h2>
	<a href="/asked_us" class="btn">Tanyakan Pada Kami</a>
</div>
{% endblock content %}

main/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Homepage</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Selamat Datang!</h1>
	<div class="make_center">
		<table align="center">
			<tr>
				<td>
					<div class="fitur">
						<a href="/infografis"><img src="{% static 'img/infografis.png' %}"></a>
						<br><br>
						<p>Infografis</p>
					</div>
				</td>
				<td>
					<div class="fitur">
						<a href="/donasi_tunai"><img src="{% static 'img/donation1.png' %}"></a>
						<br><br>
						<p>Daftar Bantuan Tunai</p>
					</div>
				</td>
				<td>
					<div class="fitur">
						<a href="/donasi_nontunai"><img src="{% static 'img/donation2.png' %}"></a>
						<br><br>
						<p>Daftar Bantuan Non Tunai</p>
					</div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="fitur">
						<a href=""><img src="{% static 'img/kritiksaran.png' %}"></a>
						<br><br>
						<p>Kritik & Saran</p>
					</div>
				</td>
				<td>
					<div class="fitur">
						<a href="/faq"><img src="{% static 'img/faq.png' %}"></a>
						<br><br>
						<p>FAQ</p>
					</div>
				</td>
				<td>
					<div class="fitur">
						<a href="/asked_us"><img src="{% static 'img/question.png' %}"></a>
						<br><br>
						<p>Pertanyaan</p>
					</div>
				</td>
			</tr>
		</table>
			
	</div>
</div>
{% endblock content %}

main/templates/infografis.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Infografis</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<div class="make_center">
		<table align="center">
			<tr>
				<td>
					<div class="fitur">
						<img src="{% static 'img/indonesia.png' %}">
						<p>Angka penyebaran Covid-19 <br>
							di Indonesia terus mengalami<br>
							kenaikan.</p>
					</div>
				</td>
				<td>
					<div class="fitur">
						<img src="{% static 'img/graph.png' %}">
						<p>Rata-rata kasus baru Covid-19 <br>
							di Indonesia mencapai 3000<br>
							kasus.</p>
					</div>
				</td>
				<td>
					<div class="fitur">
						<img src="{% static 'img/closed.png' %}">
						<p>Karena adanya PSBB, banyak<br>
							masyarakat yang tidak dapat<br>
							bekerja dan terpaksa menutup<br>
							usahanya.</p>
					</div>
				</td>
			</tr>
			<tr>
				<td>
					<p><br></p>
				</td>
				<td>
					<h2><strong>Apa yang bisa kita lakukan?</strong></h2>
				</td>
				<td><p><br></p></td>
			</tr>
			<tr>
				<td>
				<div class="fitur">
					<img src="{% static 'img/stay-at-home.png' %}">
					<p>
						Stay at home! Keluar<br>
						hanya jika ada urusan<br>
						mendesak
					</p>
				</div>
				</td>
				<td>
				<div class ="fitur">
					<img src="{% static 'img/face-mask.png' %}">
					<p>
						Jangan lupa pakai <br>
						masker jika bepergian
					</p>
				</div>
				</td>
				<td>
				<div class="fitur">
					<img src="{% static 'img/wash-your-hands.png' %}">
					<p>
						<br>Rajinlah mencuci tangan
					</p>
				</div>
				</td>
			</tr>
			<tr>
				<td>
					<p><br></p>
					
				</td>
				<td>
					<div class="fitur">
					<img src="{% static 'img/donate.png' %}">
					<h2>Bantu sesama dengan <br>
						cara berdonasi!<br><br><strong>Daftar sekarang!</strong></h2>
						<a href="/donasi_tunai" class="btn">Donasi Tunai</a>
						<a href="/donasi_nontunai" class="btn">Donasi Non Tunai</a>
					</div>
				</td>
			</tr>
			
		</table>
	</div>
</div>
{% endblock content %}

pertanyaan/templates/form_pertanyaan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Pertanyaan</title>
{% endblock meta %}

{% block content %}
  <div class="content mt-5 pt-5">
  {% if submitted %}
  <div class="make_center">
	<h1 class="title">Pertanyaan Anda Sudah Dikirim!</h1>
  	<a href="/faq" class="btn">Kembali ke FAQ</a>
  	<a href="{% url 'pertanyaan:list_asked' %}" class="btn">Daftar Pertanyaan</a>
  </div>
  
  {% else %}
  	<h1 class="title">Pertanyaan</h1>
  	<div class="form">
  		<form action="" method="POST">
			{% csrf_token %}
        <p>Nama:</p>
        <p>{{form.nama}}</p>
        <p>Email / No Handphone :</p>
				<p>{{ form.kontak }}</p>
        <p>Pertanyaan :</p>
        <p>{{form.pertanyaan}}</p>
        <input type="submit" value="Kirim" class="btn">
        <a href="{% url 'pertanyaan:list_asked' %}" class="btn">Daftar Pertanyaan</a>
		</form>
  	</div>
  {% endif %}
  </div>
{% endblock content %}

pertanyaan/templates/list_result.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Pertanyaan</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Daftar Pertanyaan</h1>
	<div class="make_center">
  		{% for i in mylist %}
	    <p><b>{{i.nama}}</b></p>
	    <p>{{i.pertanyaan}}</p>
	    <br>
	    {% endfor %}
	    <a href="/faq" class="btn">Kembali ke FAQ</a>
	</div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-custom">
    <div class="container">
    <a class="navbar-brand" href="{% url 'main:home' %}">TK1</a>
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <!-- <a class="nav-item nav-link page-scroll" href="#home">Home <span class="sr-only">(current)</span></a> -->
        <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
        <a class="nav-item nav-link" href="#contact">Contact</a>
      </div>
    </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <br><br>
  <div class="footer">
    <div class="container">
      <div class="flex_footer">
        <div class="contact_us" id="contact">
          <p>Contact Us</p>
          <p><img src="{% static 'img/phone.png' %}">	+62 8213 9003 9865</p>
        </div>
        <div>
          <p><a href="/faq">FAQ</a></p>
          <p><a href="">Kritik & Saran</a></p>
        </div>
      </div>
        <p class="make_center">Copyright Kelompok D04 Reserved</p>
      </div>
    </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>

</html>